### ISSUE TITLE
Default locale - flaky behavior

### ISSUE THREAD

**Issue by OddSquirrel** [pglombardo/PasswordPusher#633]
## 🔬 How To Reproduce

1. Set PWP__DEFAULT_LOCALE to any language other than en
2. Open PasswordPusher website
3. Content gets displayed in en sometimes in spite of the different default setting

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [X] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [X] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [X] Own server behind NPM

If applicable, what version of Password Pusher?

latest

## 📈 Expected behavior

PasswordPusher should respect the default language setting.

**Comment by pglombardo** [comment]
Hi @OddSquirrel - you're right.  Something must have broken.  I'll take a closer look soon.

**Comment by pglombardo** [comment]
This closed automatically when the fix was merged.  It should be released soon.

**Comment by pglombardo** [comment]
[Release 1.23.6](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.23.6) is building now.  This should resolve the issue.

Thanks for pointing this out!

**Comment by OddSquirrel** [comment]
You're incredible, thank you so much! 😊

**Comment by OddSquirrel** [comment]
Hi @pglombardo! Since I just needed to send another password to a recipient, I noticed that all my ENV entries in Portainer were gone for whatever reason, so put them all back in and saw that the behavior still exists—the page will always open in English, even though my `PWP__DEFAULT_LOCALE` says `de`.

Would you be able to check if there's something else possibly causing it?

**Comment by pglombardo** [comment]
Hrm sorry to hear @OddSquirrel.  There's gotta be a bug in one of the language libraries that only shows up occasionally...  I'll dig on this soon.

**Comment by pglombardo** [comment]
Filed a question in the related repo: https://github.com/enriclluelles/route_translator/issues/278

Let's see if they can point me in the right direction.

**Comment by pglombardo** [comment]
This should be it.  We now do a hard force to default locale (respecting `PWP__DEFAULT_LOCALE`) on the root page.  Let me know if it recurs. 

Fixed in [v1.26.3](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.26.3)

**Comment by OddSquirrel** [comment]
Grazie mille Pietro! 👍 Seems like this one did the trick, text now appears as expected in the chosen default language.
Your work and dedication is very much appreciated.

PS: How do I even know which version I'm really running? Granted, I put the specific version into my docker compose file this time, but until now, I just used the `release` tag and I always wondered where I could see what version that actually is.

**Comment by pglombardo** [comment]
Excellent!

> PS: How do I even know which version I'm really running? Granted, I put the specific version into my docker compose file this time, but until now, I just used the release tag and I always wondered where I could see what version that actually is.

Good question - I don't know really.  Docker tags & digest inspection but that's a hassle.  I announce on Twitter when the release tag is updated (manually).  Maybe for the next update I'll switch to Github releases to update the `release` tag so there is a visible history...
